### PR TITLE
downgraded spring boot version + Stub POST request - withRequestBody

### PR DESCRIPTION
**Pull request by prashanth-sams**

### CODE REVIEW

**Comment by prashanth-sams** [comment]
#15

**Comment by dhamo-pk** [comment]
@prashanth-sams  - We also need to downgrade `<spring-cloud.version>`, this is a mandatory and I have just double checked it.

**Comment by prashanth-sams** [comment]
ah okie; let me do it

**Comment by prashanth-sams** [comment]
@dhamo-pk pushed the required changes along with as additional task.

**Review by dhamo-pk — APPROVED** [review]

**Pull request merged**
